

export const ENDPOINTS = {
    // auth MS
    auth: {
        users: {
            getId: (id: string) => {return {url: `/users/${id}`, method: 'GET'}},
        },
        auth: {
            login: () => {return {url: `/auth/login`, method: 'POST'}},
            signup: () => {return {url: `/auth/register`, method: 'POST'}},
            refresh: () => {return {url: `/auth/refresh`, method: 'POST'}},
            verify: () => {return {url: `/auth/verify`, method: 'GET'}},
            logout: () => {return {url: `/auth/logout`, method: 'POST'}},
        },
        enterprise: {
            create: () => {return {url: `/enterprise`, method: 'POST'}},
            getAll: () => {return {url: `/enterprise`, method: 'GET'}},
            getActual: () => {return {url: `/enterprise/me`, method: 'GET'}},
            getById: (id: string) => {return {url: `/enterprise/${id}`, method: 'GET'}},
            updateEnterprise: (id: string) => {return {url: `/enterprise/${id}`, method: 'PATCH'}},
            softDelete: (id: string) => {return {url: `/enterprise/${id}`, method: 'DELETE'}},
            joinEnterprise: () => {return {url: `/enterprise/join`, method: 'POST'}},
            joinRequestUser: () => {return {url: `/enterprise/join/my-requests`, method: 'GET'}},
            cancelJoinRequest: (id: string) => {return {url: `/enterprise/join/${id}`, method: 'DELETE'}},
            joinRequestEnterprise: (id: string) => {return {url: `/enterprise/${id}/join-requests`, method: 'GET'}},
            handleJoinEnterprise: () => {return {url: `/enterprise/join/handle`, method: 'POST'}},
            leaveEnterprise: () => {return {url: `/enterprise/leave`, method: 'POST'}},
            transferEnterpriseOwnership: (id: string) => {return {url: `/enterprise/transfer-ownership/${id}`, method: 'POST'}},
            deleteEnterpriseMember: (id: string) => {return {url: `/enterprise/members/${id}`, method: 'DELETE'}},
        },
        roles: {
            create: () => {return {url: `/roles`, method: 'POST'}},
            getAll: () => {return {url: `/roles`, method: 'GET'}},
            getMine: () => {return {url: `/roles/me`, method: 'GET'}},
            getRolesPermissions: () => {return {url: `/roles/permissions`, method: 'GET'}},
            getRoleById: (id: string) => {return {url: `/roles/${id}`, method: 'GET'}},
            updateRole: (id: string) => {return {url: `/roles/${id}`, method: 'PATCH'}},
            deleteRole: (id: string) => {return {url: `/roles/${id}`, method: 'DELETE'}},
            assignRoleToUser: () => {return {url: `/roles/assign`, method: 'POST'}},
            removeRolesFromUser: () => {return {url: `/roles/remove`, method: 'POST'}},
            getUserRoles: (id: string) => {return {url: `/roles/user/${id}`, method: 'GET'}},
            addRolePermission: (roleId: string, permissionId: string) => {return {url: `/roles/${roleId}/permissions/${permissionId}`, method: 'POST'}},
            removeRolePermission: (roleId: string, permissionId: string) => {return {url: `/roles/${roleId}/permissions/${permissionId}`, method: 'DELETE'}},
        },
        profile: {
            getMyProfile: () => {return {url: `/profile/me`, method: 'GET'}},
            updateMyProfile: () => {return {url: `/profile/me`, method: 'PATCH'}},
            getMyCv: () => {return {url: `/profile/me/cv`, method: 'GET'}},
            getUserById: (userId: string) => {return {url: `/profile/user/${userId}`, method: 'GET'}},
            addExperience: () => {return {url: `/profile/experience`, method: 'POST'}},
            getMyExperiences: () => {return {url: `/profile/experience`, method: 'GET'}},
            getExperienceById: (id: string) => {return {url: `/profile/experience/${id}`, method: 'GET'}},
            updateExperience: (id: string) => {return {url: `/profile/experience/${id}`, method: 'PATCH'}},
            deleteExperience: (id: string) => {return {url: `/profile/experience/${id}`, method: 'DELETE'}},
            addEducation: () => {return {url: `/profile/education`, method: 'POST'}},
            getMyEducation: () => {return {url: `/profile/education`, method: 'GET'}},
            getEducationById: (id: string) => {return {url: `/profile/education/${id}`, method: 'GET'}},
            updateEducation: (id: string) => {return {url: `/profile/education/${id}`, method: 'PATCH'}},
            deleteEducation: (id: string) => {return {url: `/profile/education/${id}`, method: 'DELETE'}},
            addSkill: () => {return {url: `/profile/skill`, method: 'POST'}},
            getMySkills: () => {return {url: `/profile/skill`, method: 'GET'}},
            updateSkill: (id: string) => {return {url: `/profile/skill/${id}`, method: 'PATCH'}},
            deleteSkill: (id: string) => {return {url: `/profile/skill/${id}`, method: 'DELETE'}},
            endorseSkill: (id: string) => {return {url: `/profile/skill/${id}/endorse`, method: 'POST'}},
            addCertification: () => {return {url: `/profile/certification`, method: 'POST'}},
            getMyCertifications: () => {return {url: `/profile/certification`, method: 'GET'}},
            getCertificationById: (id: string) => {return {url: `/profile/certification/${id}`, method: 'GET'}},
            updateCertification: (id: string) => {return {url: `/profile/certification/${id}`, method: 'PATCH'}},
            deleteCertification: (id: string) => {return {url: `/profile/certification/${id}`, method: 'DELETE'}},
            addLanguage: () => {return {url: `/profile/language`, method: 'POST'}},
            getMyLanguages: () => {return {url: `/profile/language`, method: 'GET'}},
            updateLanguage: (id: string) => {return {url: `/profile/language/${id}`, method: 'PATCH'}},
            deleteLanguage: (id: string) => {return {url: `/profile/language/${id}`, method: 'DELETE'}},
        },
        userRelationships: {
            sendRequest: () => {return {url: `/user-relationship`, method: 'POST'}},
            handleRequest: () => {return {url: `/user-relationship/handle`, method: 'POST'}},
            getMyConnections: () => {return {url: `/user-relationship/connections`, method: 'GET'}},
            getConnectionsByType: () => {return {url: `/user-relationship/connections/type`, method: 'GET'}},
            getStats: () => {return {url: `/user-relationship/stats`, method: 'GET'}},        
            getReceivedRequests: () => {return {url: `/user-relationship/requests/received`, method: 'GET'}},
            getSentRequests: () => {return {url: `/user-relationship/requests/sent`, method: 'GET'}},
            cancelSentRequest: (id: string) => {return {url: `/user-relationship/requests/${id}/cancel`, method: 'DELETE'}},
            getBlockedUsers: () => {return {url: `/user-relationship/blocked`, method: 'GET'}},
            blockUser: (userId: string) => {return {url: `/user-relationship/block/${userId}`, method: 'POST'}},
            unblockUser: (relationshipId: string) => {return {url: `/user-relationship/unblock/${relationshipId}`, method: 'DELETE'}},
            checkRelationship: (targetUserId: string) => {return {url: `/user-relationship/check/${targetUserId}`, method: 'GET'}},
            updateRelationship: (id: string) => {return {url: `/user-relationship/${id}`, method: 'PATCH'}},
            deleteRelationship: (id: string) => {return {url: `/user-relationship/${id}`, method: 'DELETE'}},
        },
        enterprisePermissions: {
            assign: () => {return {url: `/enterprise-permission`, method: 'POST'}},
            getMine: () => {return {url: `/enterprise-permission`, method: 'GET'}},
            assignBulk: () => {return {url: `/enterprise-permission/bulk`, method: 'POST'}},
            getAvailable: () => {return {url: `/enterprise-permission/available`, method: 'GET'}},
            getByResource: () => {return {url: `/enterprise-permission/resource`, method: 'GET'}},
            updateExpiration: (id: string) => {return {url: `/enterprise-permission/${id}/expiration`, method: 'PATCH'}},
            revoke: (id: string) => {return {url: `/enterprise-permission/${id}`, method: 'DELETE'}},
            seedDefaults: () => {return {url: `/enterprise-permission/seed`, method: 'POST'}},
        },
        auditLogs: {
            getCompanyLogs: () => {return {url: `/audit-log`, method: 'GET'}},
            getMyLogs: () => {return {url: `/audit-log/me`, method: 'GET'}},
            getStats: () => {return {url: `/audit-log/stats`, method: 'GET'}},
            exportLogs: () => {return {url: `/audit-log/export`, method: 'GET'}},
            getById: (id: string) => {return {url: `/audit-log/${id}`, method: 'GET'}},
            cleanup: () => {return {url: `/audit-log/cleanup`, method: 'POST'}},
        }
    }
} as const;

export type EndpointKeys = keyof typeof ENDPOINTS;
